name: googlemaps_flutter_webservices
description: Google maps web services for flutter (Geocoding, Places, Directions, Distance Matrix, Photos, Timezone, Static Map)
version: 1.0.2
repository: https://github.com/Yrll21/googlemaps_flutter_webservices.git
homepage: https://github.com/Yrll21/googlemaps_flutter_webservices

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  http: ^1.0.0
  meta: ^1.3.0
  json_annotation: ^4.0.0

dev_dependencies:
  test: ^1.16.0
  pedantic: ^1.10.0
  build_runner: ^2.4.4
  json_serializable: ^6.7.0
  coverage: ^1.0.0
